FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

RUN dotnet tool install --global dotnet-ef --version 8.0.6

ENV PATH="${PATH}:/root/.dotnet/tools"

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

RUN dotnet ef migrations add InitialCreate --project Lyrics_Lab.csproj --startup-project Lyrics_Lab.csproj --output-dir Data/Migrations
RUN dotnet ef database update --project Lyrics_Lab.csproj --startup-project Lyrics_Lab.csproj


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

EXPOSE 8080
ENTRYPOINT ["dotnet", "Lyrics_Lab.dll"]