# Usar a imagem do .NET SDK para buildar o projeto
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar o arquivo csproj e restaurar as dependências
COPY *.csproj ./
RUN dotnet restore

# Copiar o restante dos arquivos e buildar o projeto
COPY . ./
RUN dotnet publish -c Release -o out

# Usar a imagem do runtime do .NET para rodar a aplicação
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expor a porta que a aplicação vai rodar
EXPOSE 80

# Comando para iniciar a aplicação
ENTRYPOINT ["dotnet", "Lyrics_Lab.dll"]